/* © SPIRV-Interpreter @ https://github.com/mmoult/SPIRV-Interpreter
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
#version 460 core
#extension GL_EXT_ray_tracing : enable

layout(location = 0) callableDataInEXT vec4 outColor;

void main() {
    // trivial output
	outColor = vec4(0.0, 1.0, 2.0, 3.0);
}
